application:
  name: 'eve-graphql-go'
  environment: 'test'
server:
  port: 8080
redis:
  url: '192.168.0.201'
  password: ''
  user: ''
  port: '30893'
esi:
  default:
    queryParams:
    - key: 'datasource'
      value: 'tranquility'
    - key: 'language'
      value: 'en'
    url: 'https://esi.evetech.net/latest'
jaeger:
  protocol: 'http'
  hostname: 'localhost'
  port: '14268'
  route: 'api/traces'
  sample:
    percent: 1