// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: protobuf/alliance.proto

package alliancepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Alliance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatorCorporationId  int32  `protobuf:"varint,1,opt,name=creator_corporation_id,json=creatorCorporationId,proto3" json:"creator_corporation_id,omitempty"`
	CreatorId             int32  `protobuf:"varint,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	DateFounded           string `protobuf:"bytes,3,opt,name=date_founded,json=dateFounded,proto3" json:"date_founded,omitempty"`
	ExecutorCorporationId int32  `protobuf:"varint,4,opt,name=executor_corporation_id,json=executorCorporationId,proto3" json:"executor_corporation_id,omitempty"`
	FactionId             int32  `protobuf:"varint,5,opt,name=faction_id,json=factionId,proto3" json:"faction_id,omitempty"`
	Name                  string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Ticker                string `protobuf:"bytes,7,opt,name=ticker,proto3" json:"ticker,omitempty"`
}

func (x *Alliance) Reset() {
	*x = Alliance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_alliance_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Alliance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alliance) ProtoMessage() {}

func (x *Alliance) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_alliance_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alliance.ProtoReflect.Descriptor instead.
func (*Alliance) Descriptor() ([]byte, []int) {
	return file_protobuf_alliance_proto_rawDescGZIP(), []int{0}
}

func (x *Alliance) GetCreatorCorporationId() int32 {
	if x != nil {
		return x.CreatorCorporationId
	}
	return 0
}

func (x *Alliance) GetCreatorId() int32 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *Alliance) GetDateFounded() string {
	if x != nil {
		return x.DateFounded
	}
	return ""
}

func (x *Alliance) GetExecutorCorporationId() int32 {
	if x != nil {
		return x.ExecutorCorporationId
	}
	return 0
}

func (x *Alliance) GetFactionId() int32 {
	if x != nil {
		return x.FactionId
	}
	return 0
}

func (x *Alliance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Alliance) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

var File_protobuf_alliance_proto protoreflect.FileDescriptor

var file_protobuf_alliance_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6c, 0x6c, 0x69, 0x61,
	0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x6c, 0x6c, 0x69, 0x61,
	0x6e, 0x63, 0x65, 0x70, 0x62, 0x22, 0x85, 0x02, 0x0a, 0x08, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e,
	0x63, 0x65, 0x12, 0x34, 0x0a, 0x16, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x63, 0x6f,
	0x72, 0x70, 0x6f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x14, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x72, 0x70, 0x6f,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x61, 0x74, 0x65, 0x5f,
	0x66, 0x6f, 0x75, 0x6e, 0x64, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x61, 0x74, 0x65, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x65, 0x64, 0x12, 0x36, 0x0a, 0x17, 0x65, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x72, 0x70, 0x6f, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x15, 0x65, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x72, 0x70, 0x6f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x66, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x42, 0x18, 0x5a,
	0x16, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x61, 0x6c, 0x6c,
	0x69, 0x61, 0x6e, 0x63, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_alliance_proto_rawDescOnce sync.Once
	file_protobuf_alliance_proto_rawDescData = file_protobuf_alliance_proto_rawDesc
)

func file_protobuf_alliance_proto_rawDescGZIP() []byte {
	file_protobuf_alliance_proto_rawDescOnce.Do(func() {
		file_protobuf_alliance_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_alliance_proto_rawDescData)
	})
	return file_protobuf_alliance_proto_rawDescData
}

var file_protobuf_alliance_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_alliance_proto_goTypes = []interface{}{
	(*Alliance)(nil), // 0: alliancepb.Alliance
}
var file_protobuf_alliance_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_alliance_proto_init() }
func file_protobuf_alliance_proto_init() {
	if File_protobuf_alliance_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_alliance_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Alliance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_alliance_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_alliance_proto_goTypes,
		DependencyIndexes: file_protobuf_alliance_proto_depIdxs,
		MessageInfos:      file_protobuf_alliance_proto_msgTypes,
	}.Build()
	File_protobuf_alliance_proto = out.File
	file_protobuf_alliance_proto_rawDesc = nil
	file_protobuf_alliance_proto_goTypes = nil
	file_protobuf_alliance_proto_depIdxs = nil
}
